version: "3"
services:

  back_end:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: back_end
    container_name: back_end
    restart: always
    volumes:
      - ".:/app"
    ports: ["8000:8000"]
    networks: ["stack"]

  front_end:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: front_end
    container_name: front_end
    restart: always
    volumes:
      - "./vip-login-site:/app"
    ports: ["8080:8080"]
    networks: ["stack"]
    links: ["back_end"]
    depends_on: ["back_end"]

networks:
  stack: {}

volumes:
  sqlite3_data: