services:

  back_end:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: back_end
    restart: always
    volumes:
      - "./src:/app/src"
      - "./pyproject.toml:/app/pyproject.toml"
      - "./requirements.txt:/app/requiremnts.txt"
    environment:
      ENV: "DEV"
    ports: ["8001:8001"]
    networks: ["stack"]

  front_end:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: front_end
    restart: always
    volumes:
      - "./vip-login-site:/app"
    ports: ["8000:8000"]
    networks: ["stack"]
    links: ["back_end"]
    depends_on: ["back_end"]

networks:
  stack: {}

volumes:
  sqlite3_data: